### ISSUE TITLE
invalid email addresses are an error

### ISSUE THREAD

**Issue by bdwain** [mszostok/codeowners-validator#3]
Hi,
I tried this tool out and it seems cool. But it seems like github treats a file with an invalid email address in it as an invalid file, which this didn't seem to catch. 

`/projects/foo foo@bar`

instead of 

`/projects/foo foo@bar.com`

would not work.

Just wanted to let you know in case you wanted to add in a check for that.

**Comment by mszostok** [comment]
Hi @bdwain 

Thanks for reporting that issue. I will take a look at it in the next two weeks :)

Cheers

**Comment by mszostok** [comment]
Issue fixed by adding syntax checker: https://github.com/mszostok/codeowners-validator/pull/46
