### ISSUE TITLE
Document what permissions are needed for a PAT

### ISSUE THREAD

**Issue by klauern** [mszostok/codeowners-validator#35]
**Description**

The documentation doesn't explain very well what permissions you need to grant a Personal Access Token in order to have it work with your tool.  More specific documentation around what permissions need to be granted, perhaps with a screenshot of the checkboxes, would be ideal.

**Reasons**

When it errors, it does not specify what permissions are needed, so remediating this becomes a process of trial-and-error to add more permissions to a token than is probably necessary, just to have it be able to pass one of the checks.

**Comment by mszostok** [comment]
Hi :) 
Documentation was added and merge to master:
https://github.com/mszostok/codeowners-validator/blob/master/docs/gh-token.md

if sth will be unclear/missing then please reopen the issue :)
