### ISSUE TITLE
Files checker does not support globstar patterns (**)

### ISSUE THREAD

**Issue by wilrnh** [mszostok/codeowners-validator#42]
the validator uses go's built in filepath globber, which doesn't support double-asterisk patterns (https://github.com/golang/go/issues/11862):

https://github.com/mszostok/codeowners-validator/blob/c915fc0611a4e9336a7eaf64d6e93a28a765a7fa/internal/check/file_exists.go#L27

using https://github.com/bmatcuk/doublestar or https://github.com/golang/go/issues/11862#issuecomment-694740475 seems like good fixes for now.

**Comment by mszostok** [comment]
Hi @wilrnh 

Thanks for reporting that issue, this is also a part of this problem https://github.com/mszostok/codeowners-validator/issues/22 and sometime ago I was doing an investigation about it and as a result I had fix on my local branch but forget to finish that. Your issue energized me to finish that, thanks! 😃

**Comment by wilrnh** [comment]
glad to hear! any plans for a release soon?

**Comment by wilrnh** [comment]
> glad to hear! any plans for a release soon?

ignore me, i just rtfm and saw the milestone. ill go ahead with an internal build for now. thanks for such a great project!

**Comment by mszostok** [comment]
Thanks!

Actually, I will try to do my best to close the v0.5.0 milestone this week. I will update you when the new release will be cut off :+1:

**Comment by mszostok** [comment]
Hi @wilrnh ICYMI: Yesterday I released a new v0.5.0 version of Codeowners Validator, check more [here](https://github.com/mszostok/codeowners-validator/releases/tag/v0.5.0).

Sorry for the little delay:)

**Comment by wilrnh** [comment]
very nice! thank you
