### ISSUE TITLE
410 Gone from reading https://sum.golang.org/lookup/github.com/mszostok/codeowners-validator@v0.5.1

### ISSUE THREAD

**Issue by dragonsinth** [mszostok/codeowners-validator#59]
Can't go get -u github.com/mszostok/codeowners-validator as of v0.5.0

```
~/src/mn/projects/fullstory go get -u github.com/mszostok/codeowners-validator
go: finding github.com/mszostok/codeowners-validator v0.5.1
go: finding github.com/mszostok/codeowners-validator v0.5.1
verifying github.com/mszostok/codeowners-validator@v0.5.1/go.mod: github.com/mszostok/codeowners-validator@v0.5.1/go.mod: reading https://sum.golang.org/lookup/github.com/mszostok/codeowners-validator@v0.5.1: 410 Gone
```

Directly hitting https://sum.golang.org/lookup/github.com/mszostok/codeowners-validator@v0.5.1
```
not found: create zip: malformed file path "internal/printer/testdata/TestTTYPrinterPrintSummary/Should_print_'no'_when_there_is_no_failures.golden.txt": invalid char '\''
```

It seems that sum.golang.org doesn't like this package right now.  The last one I can actually pull is v0.4.0
Unsure whether this is a bug with sum.golang.org or not.

**Comment by mszostok** [comment]
Thanks to @sgmitchell, this problem should be fixed already on master. I will create the `0.5.2` release just as a "shadow" for the `0.5.1` to allow you to vendor this pkg.

Thanks for reporting this issue!
