### ISSUE TITLE
Verify code owners against a set list of owners?

### ISSUE THREAD

**Issue by ktikku** [mszostok/codeowners-validator#81]
Hi @mszostok,

This action is quite useful for us, thanks!
I had question, can we verify/validate the code owners present in the CODEOWNERS file against against a set list of users.
I was not able to find such a feature in the documentation.

Thanks

**Comment by mszostok** [comment]
Hi @ktikku,

Currently, there is no such option. Owners are validated against GitHub. If they are present in a given org and have proper permissions, they are valid.

**Comment by mszostok** [comment]
Please re-open if this feature is really required. Currently, it lacks enough interest to be implemented in the near future.
