### ISSUE TITLE
Something is wrong.

### ISSUE THREAD

**Issue by iam-frankqiu** [mszostok/codeowners-validator#96]
**Description**

I opened a PR to node.js. The first time Actions is passed, but the second time it failed. 
I really don't know why. Is it a problem with the version of 0.4?

**Expected result**
Actions passed.

**Actual result**
Something is wrong.

**Steps to reproduce**
https://github.com/nodejs/node/pull/40281/checks?check_run_id=3787788624

**Troubleshooting**

**Comment by mszostok** [comment]
I see that pipeline are green. Please reopen if problems still occur. Using the latest version is also recommended.
